name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: [ubuntu-22.04]
    
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y asciidoc source-highlight doxygen graphviz
    - name: Run CMake+Ninja without triplet
      uses: lukka/run-cmake@v2
      with:
        cmakeGenerator: 'Ninja'  
        cmakeListsOrSettingsJson: 'CMakeListsTxtAdvanced'
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        cmakeAppendedArgs: '-DCMAKE_INSTALL_PREFIX=${{ runner.workspace }}/install'
        buildWithCMakeArgs: '-t doc install'
        buildDirectory: '${{ runner.workspace }}/build'
    - uses: actions/upload-artifact@v2
      with:
        name: capi
        path: '${{ runner.workspace }}/install/**/*'
