name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        configs: [Release, Debug]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1.4
      with:
        config: ${{ matrix.configs }}
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        cmakeAppendedArgs: '-DCMAKE_INSTALL_PREFIX=${{ runner.workspace }}/install'
        buildDirectory: '${{ runner.workspace }}/build'
    - uses: actions/upload-artifact@v2
      with:
        name: capi
        path: '${{ runner.workspace }}/install/**/*'
